name: Build and Deploy

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: windows-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'  # deploy only when pushing to main branch
        run: |
          echo Deploying to production...
          # Example: Use Windows commands to deploy (e.g., PowerShell, batch scripts)
          # Example:
          # Invoke-WebRequest -Uri "http://your-server/deploy.php" -UseBasicParsing
